package dev.mtgcraft.engine;

import forge.LobbyPlayer;
import forge.deck.CardPool;
import forge.deck.Deck;
import forge.deck.DeckSection;
import forge.deck.DeckgenUtil;
import forge.game.GameType;
import forge.game.player.RegisteredPlayer;
import forge.gamemodes.match.HostedMatch;
import forge.gui.GuiBase;
import forge.gui.interfaces.IGuiGame;
import forge.item.PaperCard;
import forge.player.GamePlayerUtil;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

/** Turns a {@link MatchSetup} into a running Card-Forge match. Mirrors Card-Forge's own lobby (GameLobby). */
public final class Matches {
    private Matches() {}

    /**
     * Builds decks and starts the match on the engine thread.
     *
     * @param guis    the GUI for each human seat index (a local {@link DuelGui} or a remote seat's GUI)
     * @param onError called with a message if a deck can't be built
     */
    public static void start(MatchSetup setup, Map<Integer, IGuiGame> guis, Consumer<String> onError) {
        start(setup, guis, onError, (Consumer<Result>) null);
    }

    /** How a game ended. {@code winningTeam} matches {@link MatchSetup#effectiveTeam}; -1 if unknown. */
    public record Result(boolean draw, int winningTeam, String winnerName) {}

    /** @param onGameOver runs on the game thread when the game ends (may be null) */
    public static void start(MatchSetup setup, Map<Integer, IGuiGame> guis, Consumer<String> onError, Consumer<Result> onGameOver) {
        ForgeEngine.runOnUi(() -> {
            try {
                startNow(setup, guis, onGameOver);
            } catch (Exception e) {
                e.printStackTrace();
                onError.accept(e.getMessage() == null ? e.toString() : e.getMessage());
            }
        });
    }

    private static void startNow(MatchSetup setup, Map<Integer, IGuiGame> guis, Consumer<Result> onGameOver) throws Exception {
        MatchSetup.Mode mode = setup.mode;
        int n = setup.seats.size();
        List<RegisteredPlayer> players = new ArrayList<>();
        Map<RegisteredPlayer, IGuiGame> guiMap = new HashMap<>();
        for (int i = 0; i < n; i++) {
            MatchSetup.Seat seat = setup.seats.get(i);
            boolean archenemy = mode == MatchSetup.Mode.ARCHENEMY && i == 0;
            Deck deck = deckFor(mode, seat, archenemy);

            Iterable<PaperCard> schemes = null, planes = null;
            if (archenemy) schemes = section(DeckgenUtil.generateSchemeDeck(), DeckSection.Schemes);
            if (mode == MatchSetup.Mode.PLANECHASE) planes = section(DeckgenUtil.generatePlanarDeck(), DeckSection.Planes);

            RegisteredPlayer rp = mode.variants.isEmpty()
                    ? new RegisteredPlayer(deck)
                    : RegisteredPlayer.forVariants(n, mode.variants, deck, schemes, archenemy, planes, (CardPool) null);
            rp.setTeamNumber(setup.effectiveTeam(i));

            LobbyPlayer lobbyPlayer = seat.ai
                    ? GamePlayerUtil.createAiPlayer(seat.name, i)
                    : GamePlayerUtil.getGuiPlayer(seat.name, i, i, false);
            players.add(rp.setPlayer(lobbyPlayer));
            if (!seat.ai) {
                IGuiGame gui = guis.get(i);
                if (gui == null) throw new IllegalStateException(seat.name + " isn't connected");
                guiMap.put(rp, gui);
            }
        }
        HostedMatch match = GuiBase.getInterface().hostMatch();
        if (onGameOver != null) {
            match.setEndGameHook(() -> {
                Result r = new Result(true, -1, "");
                try {
                    var outcome = match.getGame().getOutcome();
                    if (outcome != null && !outcome.isDraw()) {
                        var winner = outcome.getWinningLobbyPlayer();
                        r = new Result(false, outcome.getWinningTeam(), winner == null ? "" : winner.getName());
                    }
                } catch (RuntimeException ignored) {
                    // no outcome available; report a draw
                }
                onGameOver.accept(r);
            });
        }
        match.startMatch(GameType.Constructed, mode.variants, players, guiMap);
    }

    private static Deck deckFor(MatchSetup.Mode mode, MatchSetup.Seat seat, boolean archenemy) throws Exception {
        if (mode.autoDecks()) {
            GameType auto = mode.variants.iterator().next();
            return auto.autoGenerateDeck(null);
        }
        if (mode.isCommanderStyle()) {
            GameType type = mode.variants.iterator().next();
            // Own decks and themed mob decks are played as they are (casual Commander, with or without a
            // commander); otherwise build a random deck for the format.
            if (seat.deck != null && (seat.deck.kind() == DeckChoice.Kind.USER || seat.deck.kind() == DeckChoice.Kind.INLINE
                    || seat.deck.kind() == DeckChoice.Kind.THEME || seat.deck.kind() == DeckChoice.Kind.CMD_PRECON)) {
                return seat.deck.build(seat.ai);
            }
            return DeckgenUtil.generateCommanderDeck(seat.ai, type);
        }
        DeckChoice choice = seat.deck == null ? DeckChoice.colors(List.of()) : seat.deck;
        return choice.build(seat.ai);
    }

    /** The cards of one section of a generated variant deck (falls back to the main section). */
    private static Iterable<PaperCard> section(Deck deck, DeckSection section) {
        if (deck == null) return Collections.emptyList();
        CardPool pool = deck.has(section) ? deck.get(section) : deck.getMain();
        return pool == null ? Collections.emptyList() : pool.toFlatList();
    }
}
